= App DB Aufbereitung Wetterinformationen
Renato Huber
:doctype: Anleitung
:icons: font

:toc:
:toclevels: 2

== Error-Handling / Exceptions
Wenn das Programm mit unpassenden Daten versorgt wird, so muss dies abgefangen werden und der Benutzer muss über
die Situation informiert werden. Zudem sollen solche Vorfälle in einem externen Log dokumentiert werden.

Folgende Exceptions werden abgefangen:

*FileNotFoundException* +
Wenn im Verzeichnis, wo die Rohdaten liegen sollten, keine Datei vorhanden ist, so wird dies mit einer FileNotFoundException gecatched.

*IOException* +
Kann eine Datei nicht gelesen werden, so wird dies mit einer *IOExeption* gecatched.





== Unit Tests
Folgende Testcases werden durchgeführt:

*Rohdaten in falschem Dateiformat* +
Die Rohrdaten von https://opendata.swiss/de/dataset/klimamessnetz-tageswerte[opendata.swiss] kommen als .csv-Dateien
daher. Um sicherzustellen, dass das Programm richtig reagiert, wenn dies beim Einlesen nicht der Fall ist, wird dies
mit dem Testscase *"testInvalidCsvFile"* überprüft.

*Duplikate innerhalb .csv-Datensätzen* +
Eigentlich gibt es in den Rohrdaten von https://opendata.swiss/de/dataset/klimamessnetz-tageswerte[opendata.swiss] für
jede Station nur einen einzigen Tageseintrag mit Messwerten. Um Sicherzustellen, dass das Programm auf funktioniert,
wenn Duplikate vorhanden sind, wird dies mit einem Testcase überprüft. kommen als .csv-Dateien
daher. Um sicherzustellen, dass dies auch beim Einlesen der Fall ist, wird dieses Format mit dem Case *"testInvalidCsvFile"*
überprüft.




